package io.github.kmoyashi.jlaw;

/**
 * Document codes supported by the stamp tax domain.
 */
public enum StampTaxDocumentCode {
    ARTICLE1_REAL_ESTATE_TRANSFER(1),
    ARTICLE1_OTHER_TRANSFER(2),
    ARTICLE1_LAND_LEASE_OR_SURFACE_RIGHT(3),
    ARTICLE1_CONSUMPTION_LOAN(4),
    ARTICLE1_TRANSPORTATION(5),
    ARTICLE2_CONSTRUCTION_WORK(6),
    ARTICLE2_GENERAL_CONTRACT(7),
    ARTICLE3_BILL_AMOUNT_TABLE(8),
    ARTICLE3_BILL_SPECIAL_FLAT_200(9),
    ARTICLE4_SECURITY_CERTIFICATE(10),
    ARTICLE5_MERGER_OR_SPLIT(11),
    ARTICLE6_ARTICLES_OF_INCORPORATION(12),
    ARTICLE7_CONTINUING_TRANSACTION_BASIC(13),
    ARTICLE8_DEPOSIT_CERTIFICATE(14),
    ARTICLE9_TRANSPORT_CERTIFICATE(15),
    ARTICLE10_INSURANCE_CERTIFICATE(16),
    ARTICLE11_LETTER_OF_CREDIT(17),
    ARTICLE12_TRUST_CONTRACT(18),
    ARTICLE13_DEBT_GUARANTEE(19),
    ARTICLE14_DEPOSIT_CONTRACT(20),
    ARTICLE15_ASSIGNMENT_OR_ASSUMPTION(21),
    ARTICLE16_DIVIDEND_RECEIPT(22),
    ARTICLE17_SALES_RECEIPT(23),
    ARTICLE17_OTHER_RECEIPT(24),
    ARTICLE18_PASSBOOK(25),
    ARTICLE19_MISC_PASSBOOK(26),
    ARTICLE20_SEAL_BOOK(27);

    private final int code;

    StampTaxDocumentCode(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}
