# frozen_string_literal: true

require "rake/testtask"
require_relative "rake_support/vendor_rust"

task :vendor_rust do
  JLawRuby::VendorRust.prepare!(File.expand_path(__dir__))
end

task compile: :vendor_rust do
  Dir.chdir("ext/j_law_ruby") do
    ruby "extconf.rb"
    sh "make"
  end
end

task build: :vendor_rust do
  sh "gem build j_law_ruby.gemspec"
end

task :clean do
  rm_rf "vendor/rust"
  rm_rf "lib/j_law_ruby/native"

  next unless File.exist?("ext/j_law_ruby/Makefile")

  Dir.chdir("ext/j_law_ruby") do
    sh "make clean"
  end
end

Rake::TestTask.new(:test) do |t|
  t.libs << "lib"
  t.test_files = FileList["test/test_*.rb"]
end

task test: :compile
task default: :test
