# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .rb file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Ruby
# helpers directly inline like we're doing here.

require 'ffi'
require 'rbconfig'


module JLawUniffi
  def self.uniffi_in_range(i, type_name, min, max)
  raise TypeError, "no implicit conversion of #{i} into Integer" unless i.respond_to?(:to_int)
  i = i.to_int
  raise RangeError, "#{type_name} requires #{min} <= value < #{max}" unless (min <= i && i < max)
  i
end

def self.uniffi_utf8(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v = v.to_str.encode(Encoding::UTF_8)
  raise Encoding::InvalidByteSequenceError, "not a valid UTF-8 encoded string" unless v.valid_encoding?
  v
end

def self.uniffi_bytes(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v.to_str
end

  class RustBuffer < FFI::Struct
  layout :capacity, :uint64,
         :len,      :uint64,
         :data,     :pointer

  def self.alloc(size)
    return JLawUniffi.rust_call(:ffi_j_law_uniffi_rustbuffer_alloc, size)
  end

  def self.reserve(rbuf, additional)
    return JLawUniffi.rust_call(:ffi_j_law_uniffi_rustbuffer_reserve, rbuf, additional)
  end

  def free
    JLawUniffi.rust_call(:ffi_j_law_uniffi_rustbuffer_free, self)
  end

  def capacity
    self[:capacity]
  end

  def len
    self[:len]
  end

  def len=(value)
    self[:len] = value
  end

  def data
    self[:data]
  end

  def to_s
    "RustBuffer(capacity=#{capacity}, len=#{len}, data=#{data.read_bytes len})"
  end

  # The allocated buffer will be automatically freed if an error occurs, ensuring that
  # we don't accidentally leak it.
  def self.allocWithBuilder
    builder = RustBufferBuilder.new

    begin
      yield builder
    rescue => e
      builder.discard
      raise e
    end
  end

  # The RustBuffer will be freed once the context-manager exits, ensuring that we don't
  # leak it even if an error occurs.
  def consumeWithStream
    stream = RustBufferStream.new self

    yield stream

    raise RuntimeError, 'junk data left in buffer after consuming' if stream.remaining != 0
  ensure
    free
  end# The primitive String type.

  def self.allocFromString(value)
    RustBuffer.allocWithBuilder do |builder|
      builder.write value.encode('utf-8')
      return builder.finalize
    end
  end

  def consumeIntoString
    consumeWithStream do |stream|
      return stream.read(stream.remaining).force_encoding(Encoding::UTF_8)
    end
  end

  # The Record type UniBreakdownStep.

  def self.check_lower_TypeUniBreakdownStep(v)
    
    
    
    
    
  end

  def self.alloc_from_TypeUniBreakdownStep(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeUniBreakdownStep(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeUniBreakdownStep
    consumeWithStream do |stream|
      return stream.readTypeUniBreakdownStep
    end
  end

  # The Record type UniBrokerageFeeResult.

  def self.check_lower_TypeUniBrokerageFeeResult(v)
    
    
    
    
    RustBuffer.check_lower_SequenceTypeUniBreakdownStep(v.breakdown)
  end

  def self.alloc_from_TypeUniBrokerageFeeResult(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeUniBrokerageFeeResult(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeUniBrokerageFeeResult
    consumeWithStream do |stream|
      return stream.readTypeUniBrokerageFeeResult
    end
  end

  # The Record type UniConsumptionTaxResult.

  def self.check_lower_TypeUniConsumptionTaxResult(v)
    
    
    
    
    
    
  end

  def self.alloc_from_TypeUniConsumptionTaxResult(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeUniConsumptionTaxResult(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeUniConsumptionTaxResult
    consumeWithStream do |stream|
      return stream.readTypeUniConsumptionTaxResult
    end
  end

  # The Record type UniIncomeTaxResult.

  def self.check_lower_TypeUniIncomeTaxResult(v)
    
    
    
    
    RustBuffer.check_lower_SequenceTypeUniIncomeTaxStep(v.breakdown)
  end

  def self.alloc_from_TypeUniIncomeTaxResult(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeUniIncomeTaxResult(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeUniIncomeTaxResult
    consumeWithStream do |stream|
      return stream.readTypeUniIncomeTaxResult
    end
  end

  # The Record type UniIncomeTaxStep.

  def self.check_lower_TypeUniIncomeTaxStep(v)
    
    
    
    
    
    
  end

  def self.alloc_from_TypeUniIncomeTaxStep(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeUniIncomeTaxStep(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeUniIncomeTaxStep
    consumeWithStream do |stream|
      return stream.readTypeUniIncomeTaxStep
    end
  end

  # The Record type UniStampTaxResult.

  def self.check_lower_TypeUniStampTaxResult(v)
    
    
    
  end

  def self.alloc_from_TypeUniStampTaxResult(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeUniStampTaxResult(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeUniStampTaxResult
    consumeWithStream do |stream|
      return stream.readTypeUniStampTaxResult
    end
  end

  

  # The Sequence<T> type for TypeUniBreakdownStep.

  def self.check_lower_SequenceTypeUniBreakdownStep(v)
    v.each do |item|
      RustBuffer.check_lower_TypeUniBreakdownStep(item)
    end
  end

  def self.alloc_from_SequenceTypeUniBreakdownStep(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_SequenceTypeUniBreakdownStep(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequenceTypeUniBreakdownStep
    consumeWithStream do |stream|
      return stream.readSequenceTypeUniBreakdownStep
    end
  end

  # The Sequence<T> type for TypeUniIncomeTaxStep.

  def self.check_lower_SequenceTypeUniIncomeTaxStep(v)
    v.each do |item|
      RustBuffer.check_lower_TypeUniIncomeTaxStep(item)
    end
  end

  def self.alloc_from_SequenceTypeUniIncomeTaxStep(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_SequenceTypeUniIncomeTaxStep(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequenceTypeUniIncomeTaxStep
    consumeWithStream do |stream|
      return stream.readSequenceTypeUniIncomeTaxStep
    end
  end

  
end

module UniFFILib
  class ForeignBytes < FFI::Struct
    layout :len,      :int32,
           :data,     :pointer

    def len
      self[:len]
    end

    def data
      self[:data]
    end

    def to_s
      "ForeignBytes(len=#{len}, data=#{data.read_bytes(len)})"
    end
  end
end

private_constant :UniFFILib
  
# Helper for structured reading of values from a RustBuffer.
class RustBufferStream

  def initialize(rbuf)
    @rbuf = rbuf
    @offset = 0
  end

  def remaining
    @rbuf.len - @offset
  end

  def read(size)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    data = @rbuf.data.get_bytes @offset, size

    @offset += size

    data
  end

  def readU8
    unpack_from 1, 'c'
  end

  def readU16
    unpack_from 2, 'S>'
  end

  def readU64
    unpack_from 8, 'Q>'
  end

  def readBool
    v = unpack_from 1, 'c'

    return false if v == 0
    return true if v == 1

    raise InternalError, 'Unexpected byte for Boolean type'
  end

  def readString
    size = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative string length' if size.negative?

    read(size).force_encoding(Encoding::UTF_8)
  end

  # The Record type UniBreakdownStep.

  def readTypeUniBreakdownStep
    UniBreakdownStep.new(
      label: readString,
      base_amount: readU64,
      rate_numer: readU64,
      rate_denom: readU64,
      result: readU64
    )
  end

  # The Record type UniBrokerageFeeResult.

  def readTypeUniBrokerageFeeResult
    UniBrokerageFeeResult.new(
      total_without_tax: readU64,
      total_with_tax: readU64,
      tax_amount: readU64,
      low_cost_special_applied: readBool,
      breakdown: readSequenceTypeUniBreakdownStep
    )
  end

  # The Record type UniConsumptionTaxResult.

  def readTypeUniConsumptionTaxResult
    UniConsumptionTaxResult.new(
      tax_amount: readU64,
      amount_with_tax: readU64,
      amount_without_tax: readU64,
      applied_rate_numer: readU64,
      applied_rate_denom: readU64,
      is_reduced_rate: readBool
    )
  end

  # The Record type UniIncomeTaxResult.

  def readTypeUniIncomeTaxResult
    UniIncomeTaxResult.new(
      base_tax: readU64,
      reconstruction_tax: readU64,
      total_tax: readU64,
      reconstruction_tax_applied: readBool,
      breakdown: readSequenceTypeUniIncomeTaxStep
    )
  end

  # The Record type UniIncomeTaxStep.

  def readTypeUniIncomeTaxStep
    UniIncomeTaxStep.new(
      label: readString,
      taxable_income: readU64,
      rate_numer: readU64,
      rate_denom: readU64,
      deduction: readU64,
      result: readU64
    )
  end

  # The Record type UniStampTaxResult.

  def readTypeUniStampTaxResult
    UniStampTaxResult.new(
      tax_amount: readU64,
      bracket_label: readString,
      reduced_rate_applied: readBool
    )
  end

  

  

  # The Error type UniError

  def readTypeUniError
    variant = unpack_from 4, 'l>'
    
    if variant == 1
        return UniError::RegistryError.new(
            readString()
        )
    end
    if variant == 2
        return UniError::InputError.new(
            readString()
        )
    end
    if variant == 3
        return UniError::CalculationError.new(
            readString()
        )
    end

    raise InternalError, 'Unexpected variant tag for TypeUniError'
  end
  

  # The Sequence<T> type for TypeUniBreakdownStep.

  def readSequenceTypeUniBreakdownStep
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readTypeUniBreakdownStep
    end

    items
  end

  # The Sequence<T> type for TypeUniIncomeTaxStep.

  def readSequenceTypeUniIncomeTaxStep
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readTypeUniIncomeTaxStep
    end

    items
  end

  

  def unpack_from(size, format)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    value = @rbuf.data.get_bytes(@offset, size).unpack format

    @offset += size

    # TODO: verify this
    raise 'more than one element!!!' if value.size > 1

    value[0]
  end
end

private_constant :RustBufferStream
  
# Helper for structured writing of values into a RustBuffer.
class RustBufferBuilder
  def initialize
    @rust_buf = RustBuffer.alloc 16
    @rust_buf.len = 0
  end

  def finalize
    rbuf = @rust_buf

    @rust_buf = nil

    rbuf
  end

  def discard
    return if @rust_buf.nil?

    rbuf = finalize
    rbuf.free
  end

  def write(value)
    reserve(value.bytes.size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, value.bytes
    end
  end

  def write_U8(v)
    v = JLawUniffi::uniffi_in_range(v, "u8", 0, 2**8)
    pack_into(1, 'c', v)
  end

  def write_U16(v)
    v = JLawUniffi::uniffi_in_range(v, "u16", 0, 2**16)
    pack_into(2, 'S>', v)
  end

  def write_U64(v)
    v = JLawUniffi::uniffi_in_range(v, "u64", 0, 2**64)
    pack_into(8, 'Q>', v)
  end

  def write_Bool(v)
    pack_into(1, 'c', v ? 1 : 0)
  end

  def write_String(v)
    v = JLawUniffi::uniffi_utf8(v)
    pack_into 4, 'l>', v.bytes.size
    write v
  end

  # The Record type UniBreakdownStep.

  def write_TypeUniBreakdownStep(v)
    self.write_String(v.label)
    self.write_U64(v.base_amount)
    self.write_U64(v.rate_numer)
    self.write_U64(v.rate_denom)
    self.write_U64(v.result)
  end

  # The Record type UniBrokerageFeeResult.

  def write_TypeUniBrokerageFeeResult(v)
    self.write_U64(v.total_without_tax)
    self.write_U64(v.total_with_tax)
    self.write_U64(v.tax_amount)
    self.write_Bool(v.low_cost_special_applied)
    self.write_SequenceTypeUniBreakdownStep(v.breakdown)
  end

  # The Record type UniConsumptionTaxResult.

  def write_TypeUniConsumptionTaxResult(v)
    self.write_U64(v.tax_amount)
    self.write_U64(v.amount_with_tax)
    self.write_U64(v.amount_without_tax)
    self.write_U64(v.applied_rate_numer)
    self.write_U64(v.applied_rate_denom)
    self.write_Bool(v.is_reduced_rate)
  end

  # The Record type UniIncomeTaxResult.

  def write_TypeUniIncomeTaxResult(v)
    self.write_U64(v.base_tax)
    self.write_U64(v.reconstruction_tax)
    self.write_U64(v.total_tax)
    self.write_Bool(v.reconstruction_tax_applied)
    self.write_SequenceTypeUniIncomeTaxStep(v.breakdown)
  end

  # The Record type UniIncomeTaxStep.

  def write_TypeUniIncomeTaxStep(v)
    self.write_String(v.label)
    self.write_U64(v.taxable_income)
    self.write_U64(v.rate_numer)
    self.write_U64(v.rate_denom)
    self.write_U64(v.deduction)
    self.write_U64(v.result)
  end

  # The Record type UniStampTaxResult.

  def write_TypeUniStampTaxResult(v)
    self.write_U64(v.tax_amount)
    self.write_String(v.bracket_label)
    self.write_Bool(v.reduced_rate_applied)
  end

  

  # The Sequence<T> type for TypeUniBreakdownStep.

  def write_SequenceTypeUniBreakdownStep(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_TypeUniBreakdownStep(item)
    end
  end

  # The Sequence<T> type for TypeUniIncomeTaxStep.

  def write_SequenceTypeUniIncomeTaxStep(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_TypeUniIncomeTaxStep(item)
    end
  end

  

  private

  def reserve(num_bytes)
    if @rust_buf.len + num_bytes > @rust_buf.capacity
      @rust_buf = RustBuffer.reserve(@rust_buf, num_bytes)
    end

    yield

    @rust_buf.len += num_bytes
  end

  def pack_into(size, format, value)
    reserve(size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, [value].pack(format).bytes
    end
  end
end

private_constant :RustBufferBuilder

  # Error definitions
  class RustCallStatus < FFI::Struct
  layout :code,    :int8,
         :error_buf, RustBuffer

  def code
    self[:code]
  end

  def error_buf
    self[:error_buf]
  end

  def to_s
    "RustCallStatus(code=#{self[:code]})"
  end
end

# These match the values from the uniffi::rustcalls module
CALL_SUCCESS = 0
CALL_ERROR = 1
CALL_PANIC = 2


class UniError < StandardError
  class RegistryError < UniError
    def initialize(message)
        @message = message
        super()
      end

    attr_reader :message


    def to_s
     "#{self.class.name}(message=#{@message.inspect})"
    end
  end
  class InputError < UniError
    def initialize(message)
        @message = message
        super()
      end

    attr_reader :message


    def to_s
     "#{self.class.name}(message=#{@message.inspect})"
    end
  end
  class CalculationError < UniError
    def initialize(message)
        @message = message
        super()
      end

    attr_reader :message


    def to_s
     "#{self.class.name}(message=#{@message.inspect})"
    end
  end

end


# Map error modules to the RustBuffer method name that reads them
ERROR_MODULE_TO_READER_METHOD = {

  UniError => :readTypeUniError,

}

private_constant :ERROR_MODULE_TO_READER_METHOD, :CALL_SUCCESS, :CALL_ERROR, :CALL_PANIC,
                 :RustCallStatus

def self.consume_buffer_into_error(error_module, rust_buffer)
  rust_buffer.consumeWithStream do |stream|
    reader_method = ERROR_MODULE_TO_READER_METHOD[error_module]
    return stream.send(reader_method)
  end
end

class InternalError < StandardError
end

def self.rust_call(fn_name, *args)
  # Call a rust function
  rust_call_with_error(nil, fn_name, *args)
end

def self.rust_call_with_error(error_module, fn_name, *args)
  # Call a rust function and handle errors
  #
  # Use this when the rust function returns a Result<>.  error_module must be the error_module that corresponds to that Result.


  # Note: RustCallStatus.new zeroes out the struct, which is exactly what we
  # want to pass to Rust (code=0, error_buf=RustBuffer(len=0, capacity=0,
  # data=NULL))
  status = RustCallStatus.new
  args << status

  result = UniFFILib.public_send(fn_name, *args)

  case status.code
  when CALL_SUCCESS
    result
  when CALL_ERROR
    if error_module.nil?
      status.error_buf.free
      raise InternalError, "CALL_ERROR with no error_module set"
    else
      raise consume_buffer_into_error(error_module, status.error_buf)
    end
  when CALL_PANIC
    # When the rust code sees a panic, it tries to construct a RustBuffer
    # with the message.  But if that code panics, then it just sends back
    # an empty buffer.
    if status.error_buf.len > 0
      raise InternalError, status.error_buf.consumeIntoString()
    else
      raise InternalError, "Rust panic"
    end
  else
    raise InternalError, "Unknown call status: #{status.code}"
  end
end

private_class_method :consume_buffer_into_error

  # This is how we find and load the dynamic library provided by the component.
# For now we just look it up by name.
module UniFFILib
  extend FFI::Library

  
  ffi_lib File.expand_path("j_law_ruby.#{RbConfig::CONFIG['DLEXT']}", __dir__)
  

  attach_function :uniffi_j_law_uniffi_fn_func_calc_brokerage_fee,
    [:uint64, :uint16, :uint8, :uint8, :int8, :int8, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_j_law_uniffi_fn_func_calc_consumption_tax,
    [:uint64, :uint16, :uint8, :uint8, :int8, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_j_law_uniffi_fn_func_calc_income_tax,
    [:uint64, :uint16, :uint8, :uint8, :int8, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_j_law_uniffi_fn_func_calc_stamp_tax,
    [:uint64, :uint16, :uint8, :uint8, :int8, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_j_law_uniffi_rustbuffer_alloc,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_j_law_uniffi_rustbuffer_from_bytes,
    [ForeignBytes, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_j_law_uniffi_rustbuffer_free,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :void
  attach_function :ffi_j_law_uniffi_rustbuffer_reserve,
    [RustBuffer.by_value, :uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_j_law_uniffi_checksum_func_calc_brokerage_fee,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_j_law_uniffi_checksum_func_calc_consumption_tax,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_j_law_uniffi_checksum_func_calc_income_tax,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_j_law_uniffi_checksum_func_calc_stamp_tax,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :ffi_j_law_uniffi_uniffi_contract_version,
    [RustCallStatus.by_ref],
    :uint32
  
end

  # Public interface members begin here.

  
  
  # Record type UniBreakdownStep
class UniBreakdownStep
  attr_reader :label, :base_amount, :rate_numer, :rate_denom, :result

  def initialize(label:, base_amount:, rate_numer:, rate_denom:, result:)
    @label = label
    @base_amount = base_amount
    @rate_numer = rate_numer
    @rate_denom = rate_denom
    @result = result
  end

  def ==(other)
    if @label != other.label
      return false
    end
    if @base_amount != other.base_amount
      return false
    end
    if @rate_numer != other.rate_numer
      return false
    end
    if @rate_denom != other.rate_denom
      return false
    end
    if @result != other.result
      return false
    end

    true
  end
end
  
  # Record type UniBrokerageFeeResult
class UniBrokerageFeeResult
  attr_reader :total_without_tax, :total_with_tax, :tax_amount, :low_cost_special_applied, :breakdown

  def initialize(total_without_tax:, total_with_tax:, tax_amount:, low_cost_special_applied:, breakdown:)
    @total_without_tax = total_without_tax
    @total_with_tax = total_with_tax
    @tax_amount = tax_amount
    @low_cost_special_applied = low_cost_special_applied
    @breakdown = breakdown
  end

  def ==(other)
    if @total_without_tax != other.total_without_tax
      return false
    end
    if @total_with_tax != other.total_with_tax
      return false
    end
    if @tax_amount != other.tax_amount
      return false
    end
    if @low_cost_special_applied != other.low_cost_special_applied
      return false
    end
    if @breakdown != other.breakdown
      return false
    end

    true
  end
end
  
  # Record type UniConsumptionTaxResult
class UniConsumptionTaxResult
  attr_reader :tax_amount, :amount_with_tax, :amount_without_tax, :applied_rate_numer, :applied_rate_denom, :is_reduced_rate

  def initialize(tax_amount:, amount_with_tax:, amount_without_tax:, applied_rate_numer:, applied_rate_denom:, is_reduced_rate:)
    @tax_amount = tax_amount
    @amount_with_tax = amount_with_tax
    @amount_without_tax = amount_without_tax
    @applied_rate_numer = applied_rate_numer
    @applied_rate_denom = applied_rate_denom
    @is_reduced_rate = is_reduced_rate
  end

  def ==(other)
    if @tax_amount != other.tax_amount
      return false
    end
    if @amount_with_tax != other.amount_with_tax
      return false
    end
    if @amount_without_tax != other.amount_without_tax
      return false
    end
    if @applied_rate_numer != other.applied_rate_numer
      return false
    end
    if @applied_rate_denom != other.applied_rate_denom
      return false
    end
    if @is_reduced_rate != other.is_reduced_rate
      return false
    end

    true
  end
end
  
  # Record type UniIncomeTaxResult
class UniIncomeTaxResult
  attr_reader :base_tax, :reconstruction_tax, :total_tax, :reconstruction_tax_applied, :breakdown

  def initialize(base_tax:, reconstruction_tax:, total_tax:, reconstruction_tax_applied:, breakdown:)
    @base_tax = base_tax
    @reconstruction_tax = reconstruction_tax
    @total_tax = total_tax
    @reconstruction_tax_applied = reconstruction_tax_applied
    @breakdown = breakdown
  end

  def ==(other)
    if @base_tax != other.base_tax
      return false
    end
    if @reconstruction_tax != other.reconstruction_tax
      return false
    end
    if @total_tax != other.total_tax
      return false
    end
    if @reconstruction_tax_applied != other.reconstruction_tax_applied
      return false
    end
    if @breakdown != other.breakdown
      return false
    end

    true
  end
end
  
  # Record type UniIncomeTaxStep
class UniIncomeTaxStep
  attr_reader :label, :taxable_income, :rate_numer, :rate_denom, :deduction, :result

  def initialize(label:, taxable_income:, rate_numer:, rate_denom:, deduction:, result:)
    @label = label
    @taxable_income = taxable_income
    @rate_numer = rate_numer
    @rate_denom = rate_denom
    @deduction = deduction
    @result = result
  end

  def ==(other)
    if @label != other.label
      return false
    end
    if @taxable_income != other.taxable_income
      return false
    end
    if @rate_numer != other.rate_numer
      return false
    end
    if @rate_denom != other.rate_denom
      return false
    end
    if @deduction != other.deduction
      return false
    end
    if @result != other.result
      return false
    end

    true
  end
end
  
  # Record type UniStampTaxResult
class UniStampTaxResult
  attr_reader :tax_amount, :bracket_label, :reduced_rate_applied

  def initialize(tax_amount:, bracket_label:, reduced_rate_applied:)
    @tax_amount = tax_amount
    @bracket_label = bracket_label
    @reduced_rate_applied = reduced_rate_applied
  end

  def ==(other)
    if @tax_amount != other.tax_amount
      return false
    end
    if @bracket_label != other.bracket_label
      return false
    end
    if @reduced_rate_applied != other.reduced_rate_applied
      return false
    end

    true
  end
end
  

  
  

def self.calc_brokerage_fee(price, year, month, day, is_low_cost_vacant_house, is_seller)
    price = JLawUniffi::uniffi_in_range(price, "u64", 0, 2**64)
    
    
    year = JLawUniffi::uniffi_in_range(year, "u16", 0, 2**16)
    
    
    month = JLawUniffi::uniffi_in_range(month, "u8", 0, 2**8)
    
    
    day = JLawUniffi::uniffi_in_range(day, "u8", 0, 2**8)
    
    
    is_low_cost_vacant_house = is_low_cost_vacant_house ? true : false
    
    
    is_seller = is_seller ? true : false
    
    
  result = JLawUniffi.rust_call_with_error(UniError,:uniffi_j_law_uniffi_fn_func_calc_brokerage_fee,price,year,month,day,(is_low_cost_vacant_house ? 1 : 0),(is_seller ? 1 : 0))
  return result.consumeIntoTypeUniBrokerageFeeResult
end


  
  

def self.calc_consumption_tax(amount, year, month, day, is_reduced_rate)
    amount = JLawUniffi::uniffi_in_range(amount, "u64", 0, 2**64)
    
    
    year = JLawUniffi::uniffi_in_range(year, "u16", 0, 2**16)
    
    
    month = JLawUniffi::uniffi_in_range(month, "u8", 0, 2**8)
    
    
    day = JLawUniffi::uniffi_in_range(day, "u8", 0, 2**8)
    
    
    is_reduced_rate = is_reduced_rate ? true : false
    
    
  result = JLawUniffi.rust_call_with_error(UniError,:uniffi_j_law_uniffi_fn_func_calc_consumption_tax,amount,year,month,day,(is_reduced_rate ? 1 : 0))
  return result.consumeIntoTypeUniConsumptionTaxResult
end


  
  

def self.calc_income_tax(taxable_income, year, month, day, apply_reconstruction_tax)
    taxable_income = JLawUniffi::uniffi_in_range(taxable_income, "u64", 0, 2**64)
    
    
    year = JLawUniffi::uniffi_in_range(year, "u16", 0, 2**16)
    
    
    month = JLawUniffi::uniffi_in_range(month, "u8", 0, 2**8)
    
    
    day = JLawUniffi::uniffi_in_range(day, "u8", 0, 2**8)
    
    
    apply_reconstruction_tax = apply_reconstruction_tax ? true : false
    
    
  result = JLawUniffi.rust_call_with_error(UniError,:uniffi_j_law_uniffi_fn_func_calc_income_tax,taxable_income,year,month,day,(apply_reconstruction_tax ? 1 : 0))
  return result.consumeIntoTypeUniIncomeTaxResult
end


  
  

def self.calc_stamp_tax(contract_amount, year, month, day, is_reduced_rate_applicable)
    contract_amount = JLawUniffi::uniffi_in_range(contract_amount, "u64", 0, 2**64)
    
    
    year = JLawUniffi::uniffi_in_range(year, "u16", 0, 2**16)
    
    
    month = JLawUniffi::uniffi_in_range(month, "u8", 0, 2**8)
    
    
    day = JLawUniffi::uniffi_in_range(day, "u8", 0, 2**8)
    
    
    is_reduced_rate_applicable = is_reduced_rate_applicable ? true : false
    
    
  result = JLawUniffi.rust_call_with_error(UniError,:uniffi_j_law_uniffi_fn_func_calc_stamp_tax,contract_amount,year,month,day,(is_reduced_rate_applicable ? 1 : 0))
  return result.consumeIntoTypeUniStampTaxResult
end


  

  
end

